apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sockshop
  namespace: prod
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`sockshop.1b3e0f64-9c7c-4744-82b4-005a84c13fe2.dynatrace.training`)
      services:
      - kind: Service
        name: front-end-v1
        port: 8080
        weight: 50
      - kind: Service
        name: front-end-v2
        port: 8080
        weight: 50