---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carts-db-mongodata
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: carts-db
    namespace: dev
    labels:
      name: carts-db
      part-of: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: carts-db
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: carts-db
          part-of: sockshop
      spec:
        containers:
        - image: mongo:4.4
          name: carts-db
          ports:
          - containerPort: 27017
          resources: {}
          volumeMounts:
          - mountPath: /data/db
            name: carts-db-mongodata
        restartPolicy: Always
        volumes:
        - name: carts-db-mongodata
          persistentVolumeClaim:
            claimName: carts-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: dev
  labels:
    part-of: sockshop
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: carts-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carts-db-mongodata
  namespace: staging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: carts-db
    namespace: staging
    labels:
      name: carts-db
      part-of: sockshop
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: carts-db
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: carts-db
          part-of: sockshop
      spec:
        containers:
        - image: mongo:4.4
          name: carts-db
          ports:
          - containerPort: 27017
          resources: {}
          volumeMounts:
          - mountPath: /data/db
            name: carts-db-mongodata
        restartPolicy: Always
        volumes:
        - name: carts-db-mongodata
          persistentVolumeClaim:
            claimName: carts-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: staging
  labels:
    part-of: sockshop
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: carts-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: carts-db-mongodata
  namespace: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-db
  namespace: prod
  labels:
    name: carts-db
    part-of: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: carts-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: carts-db
        part-of: sockshop
    spec:
      containers:
      - image: mongo:4.4
        name: carts-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: carts-db-mongodata
      restartPolicy: Always
      volumes:
      - name: carts-db-mongodata
        persistentVolumeClaim:
          claimName: carts-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: carts-db
  namespace: prod
  labels:
    part-of: sockshop
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: carts-db